<?php

// tag-uri categorii turism intern
$_allowed_tags = array('Mare', 'Munte', 'Delta', 'Balneo', 'Conace', 'Cabane si pensiuni');

$_currency_symbol = array(
	'EUR' => '&euro;',
	'RON' => 'Lei'
);

// iconite vreme
$_weather_icons = array(
	'sunny' => 'Soare',
	'snowy' => 'Ninsoare',
);

// tip transport TM
$_tm_transport = array(
	'Flight' => 'Avion',
	'Coach' => 'Autocar',
	'Individual' => 'Individual',
);

// tip camere TM
$_tm_camere = array(
	'Simpla' => 'Simpla',
	'Dubla' => 'Dubla',
	'Apartament' => 'Apartament',
	'Vila' => 'Vila',
);

// tip masa TM
$_tm_masa = array(
	'MD' => 'Mic dejun',
	'HB' => 'Demipensiune',
	'FB' => 'Pensiune Completa',
	'AI' => 'All Inclusive',
	'UAI' => 'Ultra All Inclusive',
);

// eurosite meal codes
$_eurosite_meal_codes = array(
	0 => "Fara masa",
	1 => "All inclusive",
	2 => "Mic dejun",
	3 => "Demipensiune",
	4 => "Pensiune completa",
	5 => "Bonuri valorice",
	6 => "Selfcatering"
);

// eurosite facility codes
$_eurosite_facility_codes = array(
	1 => "Restaurant",
	2 => "Bucatarie la dispozitie",
	3 => "Sala de conferinte",
	4 => "Centru tratament balneo",
	5 => "Internet",
	6 => "Aer conditionat",
	7 => "Parcare",
	8 => "Spa-welness",
	9 => "Piscina interioara",
	10 => "Piscina exterioara",
	11 => "Piscina cu apa termala",
	12 => "Fitness",
	13 => "Teren de sport",
	14 => "Sauna",
	15 => "Jacuzzi",
	16 => "Internet in camera",
	17 => "Gratar in curte",
	18 => "Hotel pentru cupluri (+18)",
	19 => "Hotel pentru familii cu copii",
);

$_eurosite_facility_to_code = array(
	"Restaurant" => "restaurant",
	"Restaurant a la carte" => "restaurant_a_la_carte",
	"Wi-Fi" => "wifi",
	"Aer conditionat" => "air_conditioner",
	"Parcare" => "parking",
	"Parcare privata" => "parking",
	"Spa-welness" => "spa",
	"Spa" => "spa",
	"Piscina exterioara" => "pool_outside",
	"Piscina interioara" => "pool_indoor",
	"Fitness" => "fitness",
	"Internet in camera" => "internet",
	"Plaja privata" => "beach",
	"Plaja" => "beach",
	"Loc de joaca" => "kids_hotel",
	"Aqua Park" => "aqua_park",
);


$_hotel_facilities_options = array(
	'restaurant' => "Restaurant",
	'restaurant_a_la_carte' => "Restaurant a la carte",
	'pool_indoor' => "Piscina interioara",
	'pool_outside' => "Piscina exterioara",
	'spa' => "Spa",
	'wifi' => "Wi-fi",
	'internet' => "Internet",
	'aqua_park' => "Aqua Park",
	'kids_hotel' => "Facilitati copii",
	//'beach' => "Hotel plaja",
	//'beach_sand' => "Plaja cu nisip",
	'air_conditioner' => "Aer conditionat",
	'fitness' => "Fitness",
	'parking' => "Parcare",
	//'pets' => "Animale companie",
);


$_cities_from_circuits = array(
	14997 => 'Bucuresti',
	15023 => 'Cluj',
	15086 => 'Iasi',
	15234 => 'Timisoara',
	15224 => 'Targu Mures',
	15199 => 'Sibiu',
	15133 => 'Oradea',
	14944 => 'Arad',
	14954 => 'Baia Mare',
	15218 => 'Suceava',
	14951 => 'Bacau',
	9410 => 'Budapesta'
);

$_problematic_countries_with_1_day_flight = array(
	88, // Maldive
	91, // Mauritius
	135, // Seychelles
	65, // Indonezia / Bali
	113, // Oman
	152, // Tanzania
);

$_circuit_room_types = array(
	array(
		'code' => 'SB',
		'title' => 'Single',
		'min_ocupants' => 1,
		'max_ocupants' => 1,
		'min_adults' => 1,
		'max_adults' => 1,
		'min_children' => 0,
		'max_children' => 0,
	),
	array(
		'code' => 'DB',
		'title' => 'Dubla',
		'min_ocupants' => 2,
		'max_ocupants' => 3,
		'min_adults' => 1,
		'max_adults' => 3,
		'min_children' => 0,
		'max_children' => 1,
	),
	array(
		'code' => 'DBP',
		'title' => 'Dubla partaj',
		'min_ocupants' => 1,
		'max_ocupants' => 1,
		'min_adults' => 1,
		'max_adults' => 1,
		'min_children' => 0,
		'max_children' => 0,
	),
	array(
		'code' => 'DB', // 'TR'
		'title' => 'Tripla / Dubla cu pat suplimentar', // 'Tripla'
		'min_ocupants' => 3,
		'max_ocupants' => 3,
		'min_adults' => 3,
		'max_adults' => 3,
		'min_children' => 0,
		'max_children' => 0,
	),
);

$_continent_id_to_css = array(
	1 => 'africa',
	6 => 'america-nord',
	7 => 'america-sud',
	3 => 'asia',
	4 => 'oceania',
	5 => 'europa',
);


$_cruise_nights_filter = array(
	1 => '1-4',
	2 => '5-8',
	3 => '9-14',
	4 => '15-20',
	5 => '20+'
);

$_cruise_currency = array(
	'EUR' => '&euro;',
	'USD' => '$',
	'GBP' => '&pound;',
	'RON' => 'RON',
);

$_specs = array(
	"stars" => "Catalogare (stele)",
	"construction_cost" => "Cost constructie",
	"registered" => "Inregistrat in",
	"pescaj" => "Pescaj",
	"nr_cabins" => "Total cabine",
	"supr_cabins" => "Supr. cabinelor (mp)",
	"volts" => "Tensiune electrica (V)",
	"decks_acces" => "Punti accesibile",
	"nr_pools" => "Numar Piscine",
	"nr_jacuzzi" => "Numar Jacuzzi-uri",
	"nr_elevators" => "Numar Lifturi",
	"currency_used" => "Moneda utilizata",
);

$_booking_statuses = array(
	'new' => "Noua",
	'success' => "Finalizata",
	'error' => "Eroare",
	'error_payment' => "Eroare plata",
	'error_booking' => "Eroare Booking",
	'pending_approval' => "Asteptare aprobare",
);

//months
$_months = array(
	1 => 'Ianuarie',
	2 => 'Februarie',
	3 => 'Martie',
	4 => 'Aprilie',
	5 => 'Mai',
	6 => 'Iunie',
	7 => 'Iulie',
	8 => 'August',
	9 => 'Septembrie',
	10 => 'Octombrie',
	11 => 'Noiembrie',
	12 => 'Decembrie'
);

// months small
$_months_small = array(
	1 => 'Ian',
	2 => 'Feb',
	3 => 'Mar',
	4 => 'Apr',
	5 => 'Mai',
	6 => 'Iun',
	7 => 'Iul',
	8 => 'Aug',
	9 => 'Sep',
	10 => 'Oct',
	11 => 'Noi',
	12 => 'Dec'
);

// week days
$_week_days = array(
	1 => 'Luni',
	2 => 'Marti',
	3 => 'Miercuri',
	4 => 'Joi',
	5 => 'Vineri',
	6 => 'Sambata',
	7 => 'Duminica',
);
$_week_days_mysql = array(
	0 => 'Duminica',
	1 => 'Luni',
	2 => 'Marti',
	3 => 'Miercuri',
	4 => 'Joi',
	5 => 'Vineri',
	6 => 'Sambata',
);

$_judete = array(
	'Alba',
	'Arad',
	'Arges',
	'Bacau',
	'Bihor',
	'Bistrita-Nasaud',
	'Botosani',
	'Brasov',
	'Braila',
	'Bucuresti',
	'Buzau',
	'Caras-Severin',
	'Calarasi',
	'Cluj',
	'Constanta',
	'Covasna',
	'Dambovita',
	'Dolj',
	'Galati',
	'Giurgiu',
	'Gorj',
	'Harghita',
	'Hunedoara',
	'Ialomita',
	'Iasi',
	'Ilfov',
	'Maramures',
	'Mehedinti',
	'Mures',
	'Neamt',
	'Olt',
	'Prahova',
	'Satu Mare',
	'Salaj',
	'Sibiu',
	'Suceava',
	'Teleorman',
	'Timis',
	'Tulcea',
	'Vaslui',
	'Valcea',
	'Vrancea'
);

$_judete_city_insurance = array(
	1 => 'Sector 1',
	2 => 'Sector 2',
	3 => 'Sector 3',
	4 => 'Sector 4',
	5 => 'Sector 5',
	6 => 'Sector 6',
	7 => 'Alba',
	8 => 'Arad',
	9 => 'Arges',
	10 => 'Bacau',
	11 => 'Bihor',
	12 => 'Bistrita Nasaud',
	13 => 'Botosani',
	14 => 'Braila',
	15 => 'Brasov',
	16 => 'Buzau',
	17 => 'Calarasi',
	18 => 'Caras Severin',
	19 => 'Cluj',
	20 => 'Constanta',
	21 => 'Covasna',
	22 => 'Dambovita',
	23 => 'Dolj',
	24 => 'Galati',
	25 => 'Giurgiu',
	26 => 'Gorj',
	27 => 'Harghita',
	28 => 'Hunedoara',
	29 => 'Ialomita',
	30 => 'Iasi',
	31 => 'Ilfov',
	32 => 'Maramures',
	33 => 'Mehedinti',
	34 => 'Mures',
	35 => 'Neamt',
	36 => 'Olt',
	37 => 'Prahova',
	38 => 'Salaj',
	39 => 'Satu Mare',
	40 => 'Sibiu',
	41 => 'Suceava',
	42 => 'Teleorman',
	43 => 'Timis',
	44 => 'Tulcea',
	45 => 'Valcea',
	46 => 'Vaslui',
	47 => 'Vrancea',
);

$_countries = array(
    'AF' => 'Afghanistan',
    'AX' => 'Aland Islands',
    'AL' => 'Albania',
    'DZ' => 'Algeria',
    'AS' => 'American Samoa',
    'AD' => 'Andorra',
    'AO' => 'Angola',
    'AI' => 'Anguilla',
    'AQ' => 'Antarctica',
    'AG' => 'Antigua Barbuda',
    'AR' => 'Argentina',
    'AM' => 'Armenia',
    'AW' => 'Aruba',
    'AU' => 'Australia',
    'AT' => 'Austria',
    'AZ' => 'Azerbaijan',
    'BS' => 'Bahamas',
    'BH' => 'Bahrain',
    'BD' => 'Bangladesh',
    'BB' => 'Barbados',
    'BY' => 'Belarus',
    'BE' => 'Belgium',
    'BZ' => 'Belize',
    'BJ' => 'Benin',
    'BM' => 'Bermuda',
    'BT' => 'Bhutan',
    'BO' => 'Bolivia',
    'BQ' => 'Bonaire, Saint Eustatius and Saba',
    'BA' => 'Bosnia & Herzegovina',
    'BW' => 'Botswana',
    'BV' => 'Bouvet Island',
    'BR' => 'Brazil',
    'IO' => 'British Indian Ocean Territory',
    'VG' => 'British Virgin Islands',
    'BN' => 'Brunei',
    'BG' => 'Bulgaria',
    'BF' => 'Burkina Faso',
    'BI' => 'Burundi',
    'KH' => 'Cambodia',
    'CM' => 'Cameroon',
    'CA' => 'Canada',
    'CV' => 'Cape Verde',
    'KY' => 'Cayman Islands',
    'CF' => 'Central African Republic',
    'TD' => 'Chad',
    'CL' => 'Chile',
    'CN' => 'China',
    'CX' => 'Christmas Island',
    'CC' => 'Cocos Islands',
    'CO' => 'Colombia',
    'KM' => 'Comoros',
    'CK' => 'Cook Islands',
    'CR' => 'Costa Rica',
    'HR' => 'Croatia',
    'CU' => 'Cuba',
    'CW' => 'Curacao',
    'CY' => 'Cyprus',
    'CZ' => 'Czech Republic',
    'CD' => 'Democratic Republic of the Congo',
    'DK' => 'Denmark',
    'DJ' => 'Djibouti',
    'DM' => 'Dominica',
    'DO' => 'Dominican Republic',
    'TL' => 'East Timor',
    'EC' => 'Ecuador',
    'EG' => 'Egypt',
    'SV' => 'El Salvador',
    'GQ' => 'Equatorial Guinea',
    'ER' => 'Eritrea',
    'EE' => 'Estonia',
    'ET' => 'Ethiopia',
    'FK' => 'Falkland Islands',
    'FO' => 'Faroe Islands',
    'FJ' => 'Fiji',
    'FI' => 'Finland',
    'FR' => 'France',
    'GF' => 'French Guiana',
    'PF' => 'French Polynesia',
    'TF' => 'French Southern Territories',
    'GA' => 'Gabon',
    'GM' => 'Gambia',
    'GE' => 'Georgia',
    'DE' => 'Germany',
    'GH' => 'Ghana',
    'GI' => 'Gibraltar',
    'GR' => 'Greece',
    'GL' => 'Greenland',
    'GD' => 'Grenada',
    'GP' => 'Guadeloupe',
    'GU' => 'Guam',
    'GT' => 'Guatemala',
    'GG' => 'Guernsey',
    'GN' => 'Guinea',
    'GW' => 'Guinea-Bissau',
    'GY' => 'Guyana',
    'HT' => 'Haiti',
    'HM' => 'Heard Island and McDonald Islands',
    'HN' => 'Honduras',
    'HK' => 'Hong Kong',
    'HU' => 'Hungary',
    'IS' => 'Iceland',
    'IN' => 'India',
    'ID' => 'Indonesia',
    'IR' => 'Iran',
    'IQ' => 'Iraq',
    'IE' => 'Ireland',
    'IM' => 'Isle of Man',
    'IL' => 'Israel',
    'IT' => 'Italy',
    'CI' => 'Ivory Coast',
    'JM' => 'Jamaica',
    'JP' => 'Japan',
    'JE' => 'Jersey',
    'JO' => 'Jordan',
    'KZ' => 'Kazakhstan',
    'KE' => 'Kenya',
    'KI' => 'Kiribati',
    'XK' => 'Kosovo',
    'KW' => 'Kuwait',
    'KG' => 'Kyrgyzstan',
    'LA' => 'Laos',
    'LV' => 'Latvia',
    'LB' => 'Lebanon',
    'LS' => 'Lesotho',
    'LR' => 'Liberia',
    'LY' => 'Libya',
    'LI' => 'Liechtenstein',
    'LT' => 'Lithuania',
    'LU' => 'Luxembourg',
    'MO' => 'Macao',
    'MK' => 'Macedonia',
    'MG' => 'Madagascar',
    'MW' => 'Malawi',
    'MY' => 'Malaysia',
    'MV' => 'Maldives',
    'ML' => 'Mali',
    'MT' => 'Malta',
    'MH' => 'Marshall Islands',
    'MQ' => 'Martinique',
    'MR' => 'Mauritania',
    'MU' => 'Mauritius',
    'YT' => 'Mayotte',
    'MX' => 'Mexico',
    'FM' => 'Micronesia',
    'MD' => 'Moldova',
    'MC' => 'Monaco',
    'MN' => 'Mongolia',
    'ME' => 'Montenegro',
    'MS' => 'Montserrat',
    'MA' => 'Morocco',
    'MZ' => 'Mozambique',
    'MM' => 'Myanmar',
    'NA' => 'Namibia',
    'NR' => 'Nauru',
    'NP' => 'Nepal',
    'NL' => 'Netherlands',
    'NC' => 'New Caledonia',
    'NZ' => 'New Zealand',
    'NI' => 'Nicaragua',
    'NE' => 'Niger',
    'NG' => 'Nigeria',
    'NU' => 'Niue',
    'NF' => 'Norfolk Island',
    'KP' => 'North Korea',
    'MP' => 'Northern Mariana Islands',
    'NO' => 'Norway',
    'OM' => 'Oman',
    'PK' => 'Pakistan',
    'PW' => 'Palau',
    'PS' => 'Palestine',
    'PA' => 'Panama',
    'PG' => 'Papua New Guinea',
    'PY' => 'Paraguay',
    'PE' => 'Peru',
    'PH' => 'Philippines',
    'PN' => 'Pitcairn',
    'PL' => 'Poland',
    'PT' => 'Portugal',
    'PR' => 'Puerto Rico',
    'QA' => 'Qatar',
    'CG' => 'Republic of the Congo',
    'RE' => 'Reunion',
    'RO' => 'Romania',
    'RU' => 'Russia',
    'RW' => 'Rwanda',
    'BL' => 'Saint Barthelemy',
    'SH' => 'Saint Helena',
    'KN' => 'Saint Kitts and Nevis',
    'LC' => 'Saint Lucia',
    'MF' => 'Saint Martin',
    'PM' => 'Saint Pierre and Miquelon',
    'VC' => 'Saint Vincent and the Grenadines',
    'WS' => 'Samoa',
    'SM' => 'San Marino',
    'ST' => 'Sao Tome and Principe',
    'SA' => 'Saudi Arabia',
    'SN' => 'Senegal',
    'RS' => 'Serbia',
    'SC' => 'Seychelles',
    'SL' => 'Sierra Leone',
    'SG' => 'Singapore',
    'SX' => 'Sint Maarten',
    'SK' => 'Slovakia',
    'SI' => 'Slovenia',
    'SB' => 'Solomon Islands',
    'SO' => 'Somalia',
    'ZA' => 'South Africa',
    'GS' => 'South Georgia and the South Sandwich Islands',
    'KR' => 'South Korea',
    'SS' => 'South Sudan',
    'ES' => 'Spain',
    'LK' => 'Sri Lanka',
    'SD' => 'Sudan',
    'SR' => 'Suriname',
    'SJ' => 'Svalbard and Jan Mayen',
    'SZ' => 'Swaziland',
    'SE' => 'Sweden',
    'CH' => 'Switzerland',
    'SY' => 'Syria',
    'TW' => 'Taiwan',
    'TJ' => 'Tajikistan',
    'TZ' => 'Tanzania',
    'TH' => 'Thailand',
    'TG' => 'Togo',
    'TK' => 'Tokelau',
    'TO' => 'Tonga',
    'TT' => 'Trinidad and Tobago',
    'TN' => 'Tunisia',
    'TR' => 'Turkey',
    'TM' => 'Turkmenistan',
    'TC' => 'Turks and Caicos Islands',
    'TV' => 'Tuvalu',
    'VI' => 'U.S. Virgin Islands',
    'UG' => 'Uganda',
    'UA' => 'Ukraine',
    'AE' => 'United Arab Emirates',
    'GB' => 'United Kingdom',
    'US' => 'USA',
    'UM' => 'United States Minor Outlying Islands',
    'UY' => 'Uruguay',
    'UZ' => 'Uzbekistan',
    'VU' => 'Vanuatu',
    'VA' => 'Vatican',
    'VE' => 'Venezuela',
    'VN' => 'Vietnam',
    'WF' => 'Wallis and Futuna',
    'EH' => 'Western Sahara',
    'YE' => 'Yemen',
    'ZM' => 'Zambia',
    'ZW' => 'Zimbabwe',
);
